spring.application.name=backend

server.port = 8080

# Postgres connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=ecommerce_user
spring.datasource.password=Destinations@24
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──────────────────────────────────────
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
# NOTE: 'create-drop' drops and recreates tables on restart.
# We use this only in Week 1 while designing.
# Day 7 we switch to 'validate' and use Flyway migrations.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

# ── Redis ────────────────────────────────────────────────
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ── Logging ──────────────────────────────────────────────
logging.level.com.ecommerce=DEBUG
logging.level.org.springframework.security=DEBUG